{% set version = '0.2.4' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-autoslider.core
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/autoslider.core_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/autoslider.core/autoslider.core_{{ version }}.tar.gz
  sha256: 7d97c5fa24c5f8d13588b15a60a74c8308a19002935d4d25fb0d82560feea528

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    # The libstdc++.dll provided in libstdcxx v15.1.0 build h904f734_2
    # is missing `_ZSt21ios_base_library_initv`.
    # see: conda-forge/ctng-compilers-feedstock#174
    - libstdcxx !=14.3.0,!=15.1.0  # [win]
  host:
    - r-base >=4.4
    - r-assertthat >=0.2.1
    - r-checkmate >=2.3.2
    - r-cli >=3.6.3
    - r-dplyr >=1.1.4
    - r-flextable >=0.9.4
    - r-forcats >=1.0.0
    - r-ggplot2 >=3.5.1
    - r-ggpubr >=0.6.0
    - r-gridextra >=2.3
    - r-gtsummary >=2.1.0
    - r-officer >=0.3.18
    - r-rlang >=1.1.4
    - r-rlistings >=0.2.11
    - r-rtables >=0.6.12
    - r-rvg >=0.2.5
    - r-stringr >=1.5.1
    - r-survival
    - r-tern >=0.9.8
    - r-tidyr >=1.3.1
    - r-yaml >=2.3.10
  run:
    - r-base >=4.4
    - r-assertthat >=0.2.1
    - r-checkmate >=2.3.2
    - r-cli >=3.6.3
    - r-dplyr >=1.1.4
    - r-flextable >=0.9.4
    - r-forcats >=1.0.0
    - r-ggplot2 >=3.5.1
    - r-ggpubr >=0.6.0
    - r-gridextra >=2.3
    - r-gtsummary >=2.1.0
    - r-officer >=0.3.18
    - r-rlang >=1.1.4
    - r-rlistings >=0.2.11
    - r-rtables >=0.6.12
    - r-rvg >=0.2.5
    - r-stringr >=1.5.1
    - r-survival
    - r-tern >=0.9.8
    - r-tidyr >=1.3.1
    - r-yaml >=2.3.10
  run_constrained:
    - libstdcxx !=14.3.0,!=15.1.0           # [win]

test:
  commands:
    - $R -e "library('autoslider.core')"           # [not win]
    - "\"%R%\" -e \"library('autoslider.core')\""  # [win]

about:
  home: https://github.com/insightsengineering/autoslider.core
  license: Apache-2.0
  summary: The normal process of creating clinical study slides is that a statistician manually
    type in the numbers from outputs and a separate statistician to double check the
    typed in numbers. This process is time consuming, resource intensive, and error
    prone. Automatic slide generation is a solution to address these issues. It reduces
    the amount of work and the required time when creating slides, and reduces the risk
    of errors from manually typing or copying numbers from the output to slides. It
    also helps users to avoid unnecessary stress when creating large amounts of slide
    decks in a short time window.
  license_family: APACHE
  license_file:
    - LICENSE-2.0.txt

extra:
  recipe-maintainers:
    - conda-forge/r
