{% set version = "0.3.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-autoslider.core
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/autoslider.core_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/autoslider.core/autoslider.core_{{ version }}.tar.gz
  sha256: c3f3ac9c00e7c30b299a66e7d8ee3d96f8d682f73412187e56c2cbd542adb88a

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-assertthat >=0.2.1
    - r-checkmate >=2.2.0
    - r-cli >=3.6.3
    - r-dplyr >=1.1.3
    - r-flextable >=0.9.6
    - r-forcats >=1.0.0
    - r-formatters >=0.5.12
    - r-ggplot2 >=3.5.0
    - r-ggpubr >=0.6.0
    - r-gridextra >=2.3
    - r-gtsummary >=2.0.3
    - r-officer >=0.7.0
    - r-rlang >=1.1.1
    - r-rlistings >=0.2.13
    - r-rtables >=0.6.15
    - r-rvg >=0.2.5
    - r-stringr >=1.5.0
    - r-survival
    - r-tern >=0.9.10
    - r-tidyr >=1.3.0
    - r-yaml >=2.3.7
  run:
    - r-base
    - r-assertthat >=0.2.1
    - r-checkmate >=2.2.0
    - r-cli >=3.6.3
    - r-dplyr >=1.1.3
    - r-flextable >=0.9.6
    - r-forcats >=1.0.0
    - r-formatters >=0.5.12
    - r-ggplot2 >=3.5.0
    - r-ggpubr >=0.6.0
    - r-gridextra >=2.3
    - r-gtsummary >=2.0.3
    - r-officer >=0.7.0
    - r-rlang >=1.1.1
    - r-rlistings >=0.2.13
    - r-rtables >=0.6.15
    - r-rvg >=0.2.5
    - r-stringr >=1.5.0
    - r-survival
    - r-tern >=0.9.10
    - r-tidyr >=1.3.0
    - r-yaml >=2.3.7

test:
  commands:
    - $R -e "library('autoslider.core')"           # [not win]
    - "\"%R%\" -e \"library('autoslider.core')\""  # [win]

about:
  home: https://github.com/insightsengineering/autoslider.core
  license: Apache-2.0
  summary: The normal process of creating clinical study slides is that a statistician manually type in the numbers from outputs and a separate statistician to double check the typed in numbers. This process is time consuming, resource intensive, and error prone. Automatic slide generation is a solution to address these
    issues. It reduces the amount of work and the required time when creating slides, and reduces the risk of errors from manually typing or copying numbers from the output to slides. It also helps users to avoid unnecessary stress when creating large amounts of slide decks in a short time window.
  license_family: APACHE
  license_file:
    - LICENSE-2.0.txt

extra:
  recipe-maintainers:
    - conda-forge/r
